# -*- coding: utf-8 -*-
"""Innovation_Management_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFfBAcyd9W3FmHn6vZ1ZMM3Qv5dCjnK5
"""

# Install SHAP for Explainable AI
!pip install shap

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Bidirectional, Dropout, BatchNormalization, Input
from sklearn.preprocessing import MinMaxScaler
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error
import shap
import matplotlib.pyplot as plt
import pickle

# Verify GPU
print("GPU is", "available" if tf.config.list_physical_devices('GPU') else "NOT available")

# 1. Load Datasets
solar_df = pd.read_csv('Renewable.csv')
price_df = pd.read_csv('agmarknet_india_historical_prices_2024_2025.csv')

# 2. Date Formatting
solar_df['Time'] = pd.to_datetime(solar_df['Time'])
price_df['Price Date'] = pd.to_datetime(price_df['Price Date'])

# 3. Synchronize Market & Solar Data
daily_market = price_df.groupby('Price Date')['Modal Price (Rs./Quintal)'].mean().reset_index()
df = pd.merge_asof(solar_df.sort_values('Time'),
                   daily_market.sort_values('Price Date'),
                   left_on='Time', right_on='Price Date',
                   direction='backward').fillna(method='ffill').fillna(method='bfill')

# 4. Feature Engineering for R2 > 0.85
df['hour_sin'] = np.sin(2 * np.pi * df['hour']/23)
df['hour_cos'] = np.cos(2 * np.pi * df['hour']/23)
df['month_sin'] = np.sin(2 * np.pi * (df['month']-1)/11)
df['month_cos'] = np.cos(2 * np.pi * (df['month']-1)/11)

df['GHI_lag1'] = df['GHI'].shift(1)
df['Price_lag1'] = df['Modal Price (Rs./Quintal)'].shift(1)
df.fillna(0, inplace=True)

# 5. Define Market Variables (Moved here to avoid NameError later)
market_feats = ['Modal Price (Rs./Quintal)', 'Price_lag1', 'month_sin', 'month_cos']
m_X = df[market_feats]
m_y = df['Modal Price (Rs./Quintal)'].shift(-1).fillna(df['Modal Price (Rs./Quintal)'].mean())

print("Data Preparation Complete.")

# Define solar features and target
solar_feats = ['GHI', 'temp', 'humidity', 'wind_speed', 'pressure', 'hour_sin', 'hour_cos', 'month_sin', 'month_cos', 'GHI_lag1']
solar_target = 'Energy delta[Wh]'

# Scale data
scaler = MinMaxScaler(feature_range=(0, 1))
all_solar_cols = solar_feats + [solar_target]
scaled_data_for_lstm = scaler.fit_transform(df[all_solar_cols])

def create_sequences(data, time_step=24, n_features=len(solar_feats)):
    X, y = [], []
    for i in range(len(data) - time_step):
        X.append(data[i:(i + time_step), :n_features])
        y.append(data[i + time_step, n_features])
    return np.array(X), np.array(y)

time_step = 24
X_train_full, y_train_full = create_sequences(scaled_data_for_lstm, time_step)

# Define Bi-LSTM
model_solar = Sequential([
    Input(shape=(time_step, len(solar_feats))),
    Bidirectional(LSTM(100, return_sequences=True)),
    Dropout(0.3),
    Bidirectional(LSTM(50)),
    Dropout(0.3),
    Dense(1)
])
model_solar.compile(optimizer='adam', loss='mse')

# Split Point
split_idx = int(len(X_train_full) * 0.8)

# Split Solar
X_solar_train, X_solar_test = X_train_full[:split_idx], X_train_full[split_idx:]
y_solar_train, y_solar_test = y_train_full[:split_idx], y_train_full[split_idx:]

# Align and Split Market (Crucial Fix: Aligning with the windowed index)
m_X_aligned = m_X[time_step:]
m_y_aligned = m_y[time_step:]
m_X_train, m_X_test = m_X_aligned[:split_idx], m_X_aligned[split_idx:]
m_y_train, m_y_test = m_y_aligned[:split_idx], m_y_aligned[split_idx:]

print(f"Data Split: Train Size {len(X_solar_train)}, Test Size {len(X_solar_test)}")

# Train Solar
print("Training Solar Bi-LSTM...")
model_solar.fit(X_solar_train, y_solar_train, epochs=50, batch_size=64,
                validation_data=(X_solar_test, y_solar_test), verbose=1)

# Train Market
print("\nTraining Market XGBoost...")
model_market = XGBRegressor(n_estimators=500, max_depth=7, learning_rate=0.05, subsample=0.8)
model_market.fit(m_X_train, m_y_train)

print("\nAll models trained.")

# Predictions
y_s_pred = model_solar.predict(X_solar_test)
y_m_pred = model_market.predict(m_X_test)

# Metrics
final_r2_solar = r2_score(y_solar_test, y_s_pred)
final_r2_market = r2_score(m_y_test, y_m_pred)

print(f"Solar R2: {final_r2_solar:.4f} | Market R2: {final_r2_market:.4f}")

# Plotting
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1); plt.plot(y_solar_test[:100]); plt.plot(y_s_pred[:100], '--'); plt.title("Solar Actual vs Pred")
plt.subplot(1, 2, 2); plt.plot(m_y_test.values[:100]); plt.plot(y_m_pred[:100], '--'); plt.title("Market Actual vs Pred")
plt.show()

from google.colab import files
model_solar.save('solar_model_v1.h5')
model_market.save_model('market_model_v1.json')
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

files.download('solar_model_v1.h5')
files.download('market_model_v1.json')
files.download('scaler.pkl')

def test_system_prediction(sample_index=500):
    # Prepare inputs
    test_sample_solar = X_train_full[sample_index].reshape(1, 24, len(solar_feats))
    test_sample_market = m_X_aligned.iloc[[sample_index]]

    # Predict
    predicted_wh = model_solar.predict(test_sample_solar, verbose=0)[0][0]
    predicted_price = model_market.predict(test_sample_market)[0]

    # Logic
    current_angle = 15
    price_weight = predicted_price / 1000
    motor_cost_wh = 12.5

    utility_move = (predicted_wh * np.cos(np.radians(current_angle + 5)) * price_weight) - motor_cost_wh
    utility_stay = (predicted_wh * np.cos(np.radians(current_angle)) * price_weight)

    print(f"Predicted Solar: {predicted_wh:.2f} Wh | Predicted Price: Rs. {predicted_price:.2f}")
    if utility_move > utility_stay:
        print(f"DECISION: MOVE TRACKER TO {current_angle + 5}°")
    else:
        print("DECISION: HOLD POSITION")

test_system_prediction()

# Load only the architecture and weights, skip the problematic compile step
model_solar = tf.keras.models.load_model('solar_model_v1.h5', compile=False)

# Now manually compile it so it's ready to use
model_solar.compile(optimizer='adam', loss='mse')

# Load the rest as usual
model_market = XGBRegressor()
model_market.load_model('market_model_v1.json')

with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

print("Pre-trained weights loaded successfully with compile-skip fix!")
model_market_loaded = XGBRegressor()
model_market_loaded.load_model('market_model_v1.json')
with open('scaler.pkl', 'rb') as f:
    scaler_loaded = pickle.load(f)
print("Models loaded successfully.")